### ISSUE TITLE
Problem running Launch.py

### ISSUE THREAD

**Issue by GuillotineMusic** [sunshinekitty/TwitchPlaysPokemon#12]
When I try to load the file I get an error which looks like this 
![error py](https://f.cloud.github.com/assets/6945703/2415680/a1772d5e-aaf8-11e3-97e3-dd599f4f2e55.jpg)

Any ideas?

**Comment by sunshinekitty** [comment]
Are you able to run any python programs..?

**Comment by GuillotineMusic** [comment]
No I am not, even though I installed the versions of Python that you listed.

**Comment by sunshinekitty** [comment]
Can you verify your os architecture and make sure you installed the correct one?

**Comment by GuillotineMusic** [comment]
I reinstalled Python and it works now! Thank you for the advice.
