### ISSUE TITLE
Launch file opens then closes PLEASE HELP!

### ISSUE THREAD

**Issue by ghost** [sunshinekitty/TwitchPlaysPokemon#13]
Please help! I open it then it automatically closes. Please help!

**Comment by sunshinekitty** [comment]
Run via command prompt then tell me what it spits out.

**Comment by ghost** [comment]
I runned via command prompt and it just says error. I have everything installed. Please help!

**Comment by sunshinekitty** [comment]
The error is obviously what I want to see, rather than saying "help please" over and over you could try following instructions.

**Comment by ghost** [comment]
...Why did you just close it? It just said error. That's all.

**Comment by ghost** [comment]
What instructions? I don't see any instructions.

**Comment by Zarmakuizz** [comment]
If it really just says "error", then take a screenshot of the command prompt as a proof.
