### ISSUE TITLE
Keys aren't being sent to game

### ISSUE THREAD

**Issue by ghost** [sunshinekitty/TwitchPlaysPokemon#14]
Hey bud, the window becomes active, but keys aren't being sent to the game. Switching the window to something like notepad or chrome, the keys are sent. And my controls are solid and correct... I'm using windows 8.1 and that's my best bet on where my problem is.

**Comment by sunshinekitty** [comment]
I believe keybd_event is deprecated in Windows 8 which would cause issues.  I don't have a definite answer on where to look to fix the problem other than using Windows 7.  I can point you to this repo https://github.com/SavinaRoja/PyUserInput that might do the job when you replace keybd_event.
