### ISSUE TITLE
Democracy/Anarchy System?

### ISSUE THREAD

**Issue by MP2E** [sunshinekitty/TwitchPlaysPokemon#2]
I don't seem to see references to these anywhere in the code... Seems it isn't the version in use right now :< Please upload this system! I'd like to put it to use in other games

**Comment by Krushchevawn** [comment]
Im pretty sure this isnt the same version as TwitchPlaysPokemon. This is different so it doesnt have the anarchy and democracy system.

**Comment by sunshinekitty** [comment]
Krushchevawn is correct in that this is not the same version that the Twitch channel TwitchPlaysPokemon uses, this is a different setup that allows for more flexibility but hinders performance when dealing with big data things like Anarchy/Democracy mode.  I will not say this is a planned feature but I would like to see it added.  First a GUI and easier functionality are too be added.

**Comment by wreck3d** [comment]
Any update on this? @sunshinekitty 
Over a year later, so jw

EDIT: Nevermind, got my own.
However, you may still want to answer for anyone else wondering.

**Comment by sunshinekitty** [comment]
Thanks for asking here @wreck3d - unfortunately work and personal projects have kept me very occupied at the moment and this project is stale for the time being. 

Taken from the [wiki](https://github.com/sunshinekitty/TwitchPlaysPokemon/wiki/Feature-set):  
**_Unfortunately development of this project has been paused.  Unless there is significant interest of continued development on this project there will not be any._**
