### ISSUE TITLE
Implementation on Project64 Emulator

### ISSUE THREAD

**Issue by biddum1** [sunshinekitty/TwitchPlaysPokemon#21]
I have been struggling for a while to get this code to work for the N64 emulator, Project64. Any advise you can give me please? I changed a few things but I guess my first question would be, does your original code support project64?

**Comment by sunshinekitty** [comment]
The code uses the `win32api.keybd_event()` function to send keys to the active window.  I would make sure that the window is highlighted when keybd events are being sent to it, if project64 doesn't recognize these events then it won't work with the code.  

The `press()` function on line 179 in play.py can be changed to use something else if you find a different function that works with project 64.  Should you find that the latter doesn't work out for you.

**Comment by biddum1** [comment]
Hello, Thank you for the reply. Unfortunately I could not find a solution
to my problem and gave up on it... emulating N64 games is much too
difficult for my technical know-how
