### ISSUE TITLE
Using my keyboard instead of twitch chat

### ISSUE THREAD

**Issue by dylanpiera** [sunshinekitty/TwitchPlaysPokemon#22]
I have set my bot to be my username, And whenever i do that. And i type the keys x, z, start, backspace, num-6, num-8, num-4, num-2
it goes off.
Instead of when someone types a, b, start, select, up, down, right, left

Am i doing something wrong.

Also. I can only put my self as the bot. If i try and make nightbot the bot i want to use it doesn't work at all.

**Comment by sunshinekitty** [comment]
Sounds like your keybindings are off. I'm not familiar with nightbot so can't comment on that.
