### ISSUE TITLE
Having trouble

### ISSUE THREAD

**Issue by Brenttime** [sunshinekitty/TwitchPlaysPokemon#4]
Thanks for the code but I have everything correct or so I believe but I'm having issues with the ircbot.py writing to commands.txt here is the source code. http://pastebin.com/KgxvHZr9

**Comment by Brenttime** [comment]
Also I want to know if it is possible to make this work with any game so like dolphan emulator or steam.

**Comment by sunshinekitty** [comment]
Gonna need to see the error that you're getting, as for the latter question wait for next release

**Comment by Brenttime** [comment]
I'm not getting an error that is why i'm confused...Here is the console for ircbot.py http://pastebin.com/L63TGP56.

**Comment by Brenttime** [comment]
Fixed it channel name, ect were not lowercase. I feel really dumb....lol

**Comment by sunshinekitty** [comment]
Added in a fix so this is no longer an issue.
