### ISSUE TITLE
ImportError: No module named 'win32com'

### ISSUE THREAD

**Issue by Shawnt525** [sunshinekitty/TwitchPlaysPokemon#5]
Downloaded the Python link (64-bit) and performed all the listed command prompt instructions. Received an error when running Launch.py
![commandprompt](https://f.cloud.github.com/assets/1682062/2262080/51ac2396-9e56-11e3-9f13-485588f2b12d.PNG)

**Comment by ARezaK** [comment]
Import win32com.client should be import win32con.client

**Comment by ARezaK** [comment]
Nope sorry I read that wrong, you need to download the python for windows extension

**Comment by ARezaK** [comment]
Heres a link:
http://sourceforge.net/projects/pywin32/

**Comment by Shawnt525** [comment]
I didn't realize that was something I needed. I thought it was a 32-bit version of Python. I have that now and will test later.

**Comment by sunshinekitty** [comment]
Thanks Shemer77
