### ISSUE TITLE
File not found error.

### ISSUE THREAD

**Issue by MrRageface** [sunshinekitty/TwitchPlaysPokemon#6]
Traceback (most recent call last):
  File "C:\Users\Mr.Rageface\Desktop\TwitchPlaysPokemon-master\TwitchPlaysBot\La
unch.py", line 371, in <module>
    shell.Run("%s\game\%s" % (os.getcwd(), GAME))

File "<COMObject WScript.Shell>", line 2, in Run
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None,
 0, -2147024894), None)

 I'm no python programmer so I am completely clueless as to why these errors are occuring.

**Comment by Skarmy** [comment]
I'm getting almost exactly the same errors, except for the first one mine is line 382 instead of 371, and in democracy mode it change to a problem in line 489

**Comment by sunshinekitty** [comment]
delete text document in "game" folder
after typing "democracy" or "anarchy" make sure it says "Loading yourgame.gbc"
Make sure .gbc files are set to open with your emulator

**Comment by MrRageface** [comment]
Already removed the text file and the errors are occuring after it says Loading mygame.gba... Well it says Starting Mygame.gba rather than loading

And in responce to Skarmy, I think its the same error, I just removed a few empty lines to consolidate the text a little more so there was less scrolling to do.

Edit:: I was able to get the error to go away by removing the space in the name of my game from Pokemon Emerald to PokemonEmerald.gba now how ever it is not taking in any commands.

**Comment by sunshinekitty** [comment]
Thanks for the update and fix!

Do you see the commands in the command prompt? If not make sure it's printing out "Connected" to the channel you're connecting to. Line 22 of settings.txt to change this

**Comment by MrRageface** [comment]
Yea its connecting to my channel

Active code page: 65001
Sent connected message to channel #mr_rageface
:tmi.twitch.: connected to TMI
:tmi.twitch.: your host is TMI
:tmi.twitch.: this server is pretty new
:tmi.twitch.: mi.twitch.tv 0.0.1 w n
:tmi.twitch.: - tmi.twitch.tv Message of the day -
:tmi.twitch.: - not much to say here
:tmi.twitch.: End of /MOTD command
:mr_rageface:
:mr_rageface:  ##mr_rageface :mr_rageface
:mr_rageface: #mr_rageface :End of /NAMES list
:jtv: SPECIALUSER mr_rageface turbo
:jtv: USERCOLOR mr_rageface #CC0000
:jtv: EMOTESET mr_rageface [33,793]
:jtv: HISTORYEND mr_rageface
:jtv: o mr_rageface

but its not showing the commands in the command prompt althought I do see them in my irc

**Comment by MrRageface** [comment]
Since the previous post is so long I decided to write another. I found the issue 

# Anarchy Game Mode

if mode.lower() == "anarchy":
    with open("lastsaid.txt", "w") as f:
        f.write("%s") <---- Did not have %s so it was not writing to the lastsaid file to be read.

**Comment by Skarmy** [comment]
Thanks a lot, everything is cleared up for me now!

**Comment by MrRageface** [comment]
I just wanted to add this is a very nice code I wish I could write them. Would it be hard to add a parser or something that would allow commands such as down3 or left2 etc or is that in democracy mode and I just haven't looked yet =P

**Comment by sunshinekitty** [comment]
In reply to "did not have %s" that's incorrect
That command clears the file if there's anything in it from the last section

what's wrong here is
"Sent connected message to channel #mr_rageface"

Your channel name should not have the # in front of it.

**Comment by sunshinekitty** [comment]
Added ability to read file names with a space in them, check newest release.
