### ISSUE TITLE
Commands appear but no action?

### ISSUE THREAD

**Issue by OmniMe** [sunshinekitty/TwitchPlaysPokemon#7]
I've followed your instruction (as well as the video) but seem to be having an issue where the commands are not actually working (character wont move). I've connected to the IRC, it shows 'Connected' in the Twitch chat, and when I type in the chat left, right, up, down, etc. the character in game just stands still. It is recognizing Visual Boy Advance though because it will bring that window to the front when I type the command (if I were to click on say windows explorer, go to the Twitch chat, type  left, I can see the Visual Boy Advance come forward as if it were being clicked on, but the character doesn't move at all). I also see the commands in the text file. Any advice would be greatly appreciated, been trying to figure this out for quite some time but having no luck..

Thanks!

**Comment by OmniMe** [comment]
Ah, figured it out! For some reason the keybindings for Visual Boy Advance were not saving, so each time I'd restart the default's would be set (left arrow, right arrow, etc.). This issue can be closed. Good work on this by the way!

**Comment by sunshinekitty** [comment]
Thanks for the update!
