### ISSUE TITLE
ADD COMMANDS?

### ISSUE THREAD

**Issue by meligeni** [sunshinekitty/TwitchPlaysPokemon#8]
First congratz and thx for this awesome bot you have created, is really good indeed.

I wanna know if its possible to add a command if you type on the chat something like "run" you press two buttons at the same time and keep for some few seconds than it released for his own.

Eg: type on the chat "run" bot press a+b together and stay 3 second then is released.

Looking forward to see if its possible.

Congratz again and keep up the good work!
Best regards.

**Comment by sunshinekitty** [comment]
Sorry but this is outside of the scope of this project, thanks for the kind feedback and interest in my project!
